[package]
name = "RinR"
version = "0.1.1"
edition = "2021"


[dependencies]
tokio = { version = "1.20.1", features = [
        "macros",
        "rt-multi-thread",]}
serenity = { version="0.11.5", default-features = false, features = ["utils", "client", "gateway", "rustls_backend", "model", "unstable_discord_api", "cache", "voice"]}
strum = { version = "0.24.1", features = ["derive"]}
strum_macros = "0.24.3"
async-mutex = "1.4.0"
regex = "1.6.0"
rustube = "0.5.0"
hrtime = "0.2.0"
songbird = { version="0.3.0", features = ["driver-core"]}
audiopus_sys = "0.2.2"
dotenv = "0.15.0"
rand = "0.8.5"

[profile.dev]
opt-level = 0
debug=1

[profile.release]
opt-level = 3